// Oppgave 2
// ...
const SETTINGS_WATCH_GET_USER = 'MODULES/SETTINGS/USER/WATCH_GET_USER';
const SETTINGS_WATCH_GET_USERS = 'MODULES/SETTINGS/USER/WATCH_GET_USERS';
const GET_USERS = 'MODULES/SETTINGS/USER/GET_USERS';
const GET_USERS_SUCCESS = 'MODULES/SETTINGS/USER/GET_USERS_SUCCESS';
const GET_USERS_FAILED = 'MODULES/SETTINGS/USER/GET_USERS_FAILED';

export default {
  SETTINGS_WATCH_GET_USER,
  SETTINGS_WATCH_GET_USERS,
  GET_USERS,
  GET_USERS_SUCCESS,
  GET_USERS_FAILED,
};
