export const SETTINGS_WATCH_GET_USERS = 'SETTINGS/WATCH_GET_USERS';
export const SETTINGS_WATCH_GET_USER = 'SETTINGS/WATCH_GET_USERS';
export const SETTINGS_GET_USERS = 'SETTINGS_GET_USERS';
export const SETTINGS_GET_USERS_SUCCESS = 'SETTINGS_GET_USERS_SUCCESS';
export const SETTINGS_GET_USERS_FAILED = 'SETTINGS_GET_USERS_FAILED';
export const SETTINGS_GET_USER = 'SETTINGS_GET_USER';
export const SETTINGS_GET_USER_SUCCESS = 'SETTINGS_GET_USER_SUCCESS';
export const SETTINGS_GET_USER_FAILED = 'SETTINGS_GET_USER_FAILED';
