// Oppgave 2
// ...
const SETTINGS_WATCH_GET_USER = 'MODULES/SETTINGS/USER/WATCH_GET_USER';
const SETTINGS_WATCH_GET_USERS = 'MODULES/SETTINGS/USER/WATCH_GET_USERS';

export default {
  SETTINGS_WATCH_GET_USER,
  SETTINGS_WATCH_GET_USERS,
};
