const SETTINGS_GET_USER = 'MODULES/SETTINGS/USER/SETTINGS_GET_USER';
const SETTINGS_GET_USERS = 'MODULES/SETTINGS/USER/SETTINGS_GET_USERS';
const SETTINGS_GET_USERS_FAILED = 'MODULES/SETTINGS/USER/SETTINGS_GET_USERS_FAILED';
const SETTINGS_GET_USERS_SUCCESS = 'MODULES/SETTINGS/USER/SETTINGS_GET_USERS_SUCCESS';
const SETTINGS_GET_USER_FAILED = 'MODULES/SETTINGS/USER/SETTINGS_GET_USER_FAILED';
const SETTINGS_GET_USER_SUCCESS = 'MODULES/SETTINGS/USER/SETTINGS_GET_USER_SUCCESS';
const SETTINGS_WATCH_GET_USER = 'MODULES/SETTINGS/USER/WATCH_GET_USER';
const SETTINGS_WATCH_GET_USERS = 'MODULES/SETTINGS/USER/WATCH_GET_USERS';

export default {
  SETTINGS_GET_USER,
  SETTINGS_GET_USERS,
  SETTINGS_GET_USERS_FAILED,
  SETTINGS_GET_USERS_SUCCESS,
  SETTINGS_GET_USER_FAILED,
  SETTINGS_GET_USER_SUCCESS,
  SETTINGS_WATCH_GET_USER,
  SETTINGS_WATCH_GET_USERS,
};
