const ADD_TODO = 'MODULES/TODO/ADD_TODO';
const SET_VISIBILITY_FILTER = 'MODULES/TODO/SET_VISIBILITY_FILTER';
const TOGGLE_TODO = 'MODULES/TODO/TOGGLE_TODO';

export const VisibilityFilters = {
    SHOW_ACTIVE: 'SHOW_ACTIVE',
    SHOW_ALL: 'SHOW_ALL',
    SHOW_COMPLETED: 'SHOW_COMPLETED',
};

export default {
    ADD_TODO,
    SET_VISIBILITY_FILTER,
    TOGGLE_TODO,
};
